//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planting()
        {
            this.Accounts = new HashSet<Account>();
            this.Cares = new HashSet<Care>();
        }
    
        public int PlantingID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> TreeID { get; set; }
        public Nullable<System.DateTime> DatePlanted { get; set; }
        public Nullable<int> NumberPlanted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Care> Cares { get; set; }
        public virtual Tree Tree { get; set; }
    }
}
