//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tree()
        {
            this.Plantings = new HashSet<Planting>();
        }
    
        public int TreeID { get; set; }
        public string TreeName { get; set; }
        public string TreeDescription { get; set; }
        public Nullable<int> DemandID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> TreeLocationID { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planting> Plantings { get; set; }
        public virtual TreeDemand TreeDemand { get; set; }
        public virtual TreeLocation TreeLocation { get; set; }
        public virtual TreeType TreeType { get; set; }
    }
}
