//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserLocationID { get; set; }
        public int Type { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PlantingID { get; set; }
    
        public virtual Planting Planting { get; set; }
        public virtual UserLocation UserLocation { get; set; }
    }
}
